var myChart = echarts.init(document.getElementById('relationgraph'));
option = {
    backgroundColor: new echarts.graphic.RadialGradient(0.3, 0.3, 0.8, [{
        offset: 0,
        color: '#f7f8fa'
    }, {
        offset: 1,
        color: '#cdd0d5'
    }]),
    title: {
        text: "",
        subtext: "",
        top: "top",
        left: "center"
    },
    tooltip: {},
    legend: [{}],
    toolbox: {
    },
    animationDuration: 3000,
    animationEasingUpdate: 'quinticInOut',

    series: [{
        name: 'C语言',
        type: 'graph',
        layout: 'force',

        force: {
            repulsion: 300
        },
        data: [{
            "name": "C语言",
            // "x": 0,
            // y: 0,
            "symbolSize": 130,
            "draggable": "true",
            "value": 27

        }, {
            "name": "数据类型",
            "value": 15,
            "symbolSize": 60,
            "category": "数据类型",
            "draggable": "true"
        }, {
            "name": "语句",
            "symbolSize": 20,
            "category": "数据类型",
            "draggable": "true",
            "value": 1
        }, {
            "name": "基本类型",
            "symbolSize": 30,
            "category": "数据类型",
            "draggable": "true",
            "value": 1
        }, {
            "name": "作用域",
            "symbolSize": 15,
            "category": "数据类型",
            "draggable": "true",
            "value": 1
        }, {
            "name": "控制语句",
            "value": 60,
            "symbolSize": 60,
            "category": "控制语句",
            "draggable": "true"
        }, {
            "name": "动态内存分配",
            "symbolSize": 50,
            "category": "控制语句",
            "draggable": "true",
            "value": 1
        }, {
            "name": "控制语法",
            "symbolSize": 3,
            "category": "控制语句",
            "draggable": "true",
            "value": 1
        }, {
            "name": "结构和联合",
            "value": 5,
            "symbolSize": 40,
            "category": "结构和联合",
            "draggable": "true"
        }, {
            "name": "结构",
            "symbolSize": 3,
            "category": "结构和联合",
            "draggable": "true",
            "value": 1
        }, {
            "name": "联合",
            "symbolSize": 7,
            "category": "结构和联合",
            "draggable": "true",
            "value": 1
        }, {
            "name": "数组",
            "value": 40,
            "symbolSize": 18,
            "category": "数组",
            "draggable": "true"
        }, {
            "name": "一维数组",
            "symbolSize": 20,
            "category": "数组",
            "draggable": "true",
            "value": 1
        }, {
            "name": "多维数组",
            "symbolSize": 25,
            "category": "数组",
            "draggable": "true",
            "value": 1
        }, {
            "name": "结构体",
            "value": 8,
            "symbolSize": 25,
            "category": "结构体",
            "draggable": "true"
        }, {
            "name": "定义与使用结构体",
            "symbolSize": 5,
            "category": "结构体",
            "draggable": "true",
            "value": 1
        }, {
            "name": "文件",
            "value": 5,
            "symbolSize": 30,
            "category": "文件",
            "draggable": "true"
        }, {
            "name": "文件操作",
            "symbolSize": 7,
            "category": "文件",
            "draggable": "true",
            "value": 1
        }, {
            "name": "运算符",
            "value": 30,
            "symbolSize": 30,
            "category": "运算符",
            "draggable": "true"
        }, {
            "name": "关系运算符",
            "symbolSize": 3,
            "category": "运算符",
            "draggable": "true",
            "value": 1
        }, {
            "name": "逻辑运算符",
            "symbolSize": 10,
            "category": "运算符",
            "draggable": "true",
            "value": 1
        }, {
            "name": "指针",
            "value": 20,
            "symbolSize": 30,
            "category": "指针",
            "draggable": "true"
        }, {
            "name": "指针类型",
            "symbolSize": 3,
            "category": "指针",
            "draggable": "true",
            "value": 1
        }, {
            "name": "指针使用",
            "symbolSize": 3,
            "category": "指针",
            "draggable": "true",
            "value": 1
        }, {
            "name": "基本概念",
            "value": 6,
            "symbolSize": 18,
            "category": "基本概念",
            "draggable": "true"
        }, {
            "name": "开发环境",
            "symbolSize": 5,
            "category": "基本概念",
            "draggable": "true",
            "value": 1
        }, {
            "name": "语法规则",
            "symbolSize": 3,
            "category": "基本概念",
            "draggable": "true",
            "value": 1
        }, {
            "name": "函数库",
            "value": 6,
            "symbolSize": 18,
            "category": "函数库",
            "draggable": "true"
        }, {
            "name": "标准函数库",
            "symbolSize": 3,
            "category": "函数库",
            "draggable": "true",
            "value": 1

        }],
        links: [{
            "source": "C语言",
            "target": "数据类型"
        }, {
            "source": "数据类型",
            "target": "语句"
        }, {
            "source": "数据类型",
            "target": "基本类型"
        }, {
            "source": "数据类型",
            "target": "作用域"
        }, {
            "source": "C语言",
            "target": "控制语句"
        }, {
            "source": "控制语句",
            "target": "动态内存分配"
        }, {
            "source": "控制语句",
            "target": "控制语法"
        }, {
            "source": "C语言",
            "target": "结构和联合"
        }, {
            "source": "结构和联合",
            "target": "结构"
        }, {
            "source": "结构和联合",
            "target": "联合"
        }, {
            "source": "C语言",
            "target": "数组"
        }, {
            "source": "数组",
            "target": "一维数组"
        }, {
            "source": "数组",
            "target": "多维数组"
        }, {
            "source": "C语言",
            "target": "结构体"
        }, {
            "source": "结构体",
            "target": "定义与使用结构体"
        }, {
            "source": "C语言",
            "target": "文件"
        }, {
            "source": "文件",
            "target": "文件操作"
        }, {
            "source": "C语言",
            "target": "运算符"
        }, {
            "source": "运算符",
            "target": "关系运算符"
        }, {
            "source": "运算符",
            "target": "逻辑运算符"
        }, {
            "source": "C语言",
            "target": "指针"
        }, {
            "source": "指针",
            "target": "指针类型"
        }, {
            "source": "指针",
            "target": "指针使用"
        }, {
            "source": "C语言",
            "target": "基本概念"
        }, {
            "source": "基本概念",
            "target": "开发环境"
        }, {
            "source": "基本概念",
            "target": "语法规则"
        }, {
            "source": "C语言",
            "target": "函数库"
        }, {
            "source": "函数库",
            "target": "标准函数库"
        }, {
            "source": "C语言",
            "target": "法学院"

        }],
        categories: [{
            'name': '数据类型'
        }, {
            'name': '控制语句'
        }, {
            'name': '结构和联合'
        }, {
            'name': '数组'
        }, {
            'name': '结构体'
        }, {
            'name': '文件'
        }, {
            'name': '运算符'
        }, {
            'name': '指针'
        }, {
            'name': '基本概念'
        }, {
            'name': '函数库'
        }, {

        }],
        focusNodeAdjacency: true,
        roam: true,
        label: {
            normal: {

                show: true,
                position: 'top',

            }
        },
        lineStyle: {
            normal: {
                color: 'source',
                curveness: 0,
                type: "solid"
            }
        }
    }]
};
myChart.setOption(option);

window.onresize = function () {
    //重置容器高宽
    resizeWorldMapContainer();
    myChart.resize();
};